repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python hooks (Backend)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^backend/
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^backend/
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203,W503",
          "--exclude=migrations,__pycache__,.git,venv,.venv"
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies: [types-all]
        args: [
          "--ignore-missing-imports",
          "--disallow-untyped-defs",
          "--no-implicit-optional"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^backend/
        args: ["-r", "-f", "json", "-o", "bandit-report.json"]
        exclude: ^backend/tests/

  # JavaScript/TypeScript hooks (Frontend)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/replo/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]
        exclude: |
          (?x)^(
            frontend/replo/\.next/|
            frontend/replo/node_modules/|
            frontend/replo/out/|
            frontend/replo/build/|
            frontend/replo/dist/
          )

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/replo/
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - eslint@8.56.0
          - "@typescript-eslint/eslint-plugin@6.21.0"
          - "@typescript-eslint/parser@6.21.0"
          - "eslint-config-next@14.0.4"
        exclude: |
          (?x)^(
            frontend/replo/\.next/|
            frontend/replo/node_modules/|
            frontend/replo/out/|
            frontend/replo/build/|
            frontend/replo/dist/
          )

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [
          "--ignore", "DL3008",  # Pin versions in apt get install
          "--ignore", "DL3009",  # Delete the apt-get lists after installing
          "--ignore", "DL3015",  # Avoid additional packages by specifying --no-install-recommends
        ]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            \.env\.example|
            package-lock\.json|
            yarn\.lock|
            poetry\.lock
          )$

  # Commit message formatting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(yaml|yml)$
        exclude: |
          (?x)^(
            \.github/workflows/|
            docker-compose.*\.yml$
          )

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false